---
title: "Anime Alchemy"
author: "Zehaan Naik"
format: html
editor: visual
---

## Introduction

The term "Anime" refers to all animated motion pictures that are produced in Japan. This is a booming industry with an ever-increasing audience and rising popularity. Naturally, this becomes an excellent opportunity for studios to make massive profits and an exciting field for one to study.

Anime Alchemy is a data visualization app that helps you analyze and compare the performance of various Anime series with several variables that define them. This application aims to help producers develop the best broadcasting and advertising model to ensure the success of their new program.

However, before diving into the application, we should first understand and explore the data set.

## Data

The data set we will be using for our analysis comprises the top 1000 Anime shows on the website[ MyAnimeList](https://myanimelist.net/topanime.php). We shall talk more about scrapping the data set in a later section.

As mentioned, the data set comprises 1000 observations described using 38 variables. We can divide these variables broadly into two categories: numerical and categorical.

##### Numerical Variables: 

These are the columns of our data set that have numerical values associated with them---for example, rating, number of likes, active viewers, etc.

These variables help us mathematically analyze the performance of several substrata of data points. Here is a brief description of all the columns that we have used in our analysis:

1.  [**Rating (Score):**]{.underline}

This is the average rating given to the show by everyone who rated the show. An important thing to note is that a high rating need not imply a more extensive audience size or popularity. The reason is that ten people can rate one show to be 9/10. However, another show might be rated by 100 people with a rating of 8.5. As a producer, you might favor the latter over the former.

2.  [**Number of Votes:**]{.underline}

This is the number of votes the show received on the website in a poll where users were asked about their top 10 favorite anime shows.

3.  [**Number of Favourites:**]{.underline}

This is the number of users who have marked a particular show as one of their favorites on the website.

4.  [**Number of Active Viewers:**]{.underline}

The number of people have watched over ten episodes of one particular show. Note that it is essential to distinguish between a viewer who has simply watched a single episode of a show and one who continuously watches the show. As a producer, we are primarily interested in the latter category predominantly.

5.  [**Number of Episodes:**]{.underline}

The number of episodes per season for a particular show.

6.  [**Duration Per Episode:**]{.underline}

The average duration per episode for the show.

(NOTE: Variables 5 and 6 are often used as grouping variables to analyze what range of episode number and duration sits well with a particular target audience.)

7.  [**Color Composition:**]{.underline}

We analyzed the posters for all the shows and studied the color composition of all the posters regarding their percentage RGB composition. We stored these values in separate columns to use as both grouping parameters and analysis parameters to explore various questions of possible co-relations between poster color composition and other parameters.

##### Categorical Variables:

These columns of our data set have non-numerical values such as names, seasons, origins, etc. We\'ve used these values as grouping parameters to subset our data and observe various trends that emerge in such observations. Here is a brief description of all the groups that we have used:

1.  [**Source:**]{.underline}

Every anime has a source from which it is inspired. For example, we have \"One Piece\" inspired by Manga. Similarly, other sources may include games and comics; some might be original works.

2.  [**Genre:**]{.underline}

The genre of the show. It has categories like action, adventure, drama and comedy.

3.  [**Season of Premier:**]{.underline}

What season of the year was the anime premiered in? For example, it is a common understanding that shows meant for children perform better when released in summer. This is because many children are eager to consume TV content during their vacations. 

4.  [**Day of Telecast:**]{.underline}

The day of the week on which the show is telecasted.

5.  [**Target Demographic:**]{.underline}

The age section of the audience that the show is aimed at. For example, an anime series like \"Shin-chan\" is targeted toward a younger audience than compared to a series like \"Full Metal Alchemist.\"

6.  [**Censorboard Rating:**]{.underline}

The age group that the censor board of Japan deems the show safe for.

## Obtaining Data

## Biases in Our Data

{{< pagebreak >}}

## Key Questions

## Key Visualizations

{{< pagebreak >}}

## Conclusion

## References 
